# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(841, 546)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Preprocessing = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Preprocessing.sizePolicy().hasHeightForWidth())
        self.Preprocessing.setSizePolicy(sizePolicy)
        self.Preprocessing.setObjectName("Preprocessing")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Preprocessing)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.Preprocessing)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.PrePro_Input = QtWidgets.QLineEdit(self.Preprocessing)
        self.PrePro_Input.setObjectName("PrePro_Input")
        self.horizontalLayout_34.addWidget(self.PrePro_Input)
        self.PrePro_Input_S = QtWidgets.QPushButton(self.Preprocessing)
        self.PrePro_Input_S.setMaximumSize(QtCore.QSize(30, 16777215))
        self.PrePro_Input_S.setObjectName("PrePro_Input_S")
        self.horizontalLayout_34.addWidget(self.PrePro_Input_S)
        self.verticalLayout_2.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.RawNav = QtWidgets.QCheckBox(self.Preprocessing)
        self.RawNav.setObjectName("RawNav")
        self.horizontalLayout_3.addWidget(self.RawNav)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.Preprocessing)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.TextRefPath = QtWidgets.QLineEdit(self.Preprocessing)
        self.TextRefPath.setEnabled(False)
        self.TextRefPath.setObjectName("TextRefPath")
        self.horizontalLayout_36.addWidget(self.TextRefPath)
        self.TextRefPath_S = QtWidgets.QPushButton(self.Preprocessing)
        self.TextRefPath_S.setEnabled(False)
        self.TextRefPath_S.setMaximumSize(QtCore.QSize(30, 16777215))
        self.TextRefPath_S.setObjectName("TextRefPath_S")
        self.horizontalLayout_36.addWidget(self.TextRefPath_S)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_36)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_4 = QtWidgets.QLabel(self.Preprocessing)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.PrePro_OutputPath = QtWidgets.QLineEdit(self.Preprocessing)
        self.PrePro_OutputPath.setObjectName("PrePro_OutputPath")
        self.horizontalLayout_37.addWidget(self.PrePro_OutputPath)
        self.PrePro_OutputPath_S = QtWidgets.QPushButton(self.Preprocessing)
        self.PrePro_OutputPath_S.setMaximumSize(QtCore.QSize(30, 16777215))
        self.PrePro_OutputPath_S.setObjectName("PrePro_OutputPath_S")
        self.horizontalLayout_37.addWidget(self.PrePro_OutputPath_S)
        self.verticalLayout_2.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.Preprocessing)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.NavName = QtWidgets.QLineEdit(self.Preprocessing)
        self.NavName.setObjectName("NavName")
        self.horizontalLayout.addWidget(self.NavName)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.CopyImage = QtWidgets.QCheckBox(self.Preprocessing)
        self.CopyImage.setObjectName("CopyImage")
        self.horizontalLayout_2.addWidget(self.CopyImage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.PrePro_run = QtWidgets.QPushButton(self.Preprocessing)
        self.PrePro_run.setObjectName("PrePro_run")
        self.verticalLayout_2.addWidget(self.PrePro_run)
        self.PrePro_Debug = QtWidgets.QTextBrowser(self.Preprocessing)
        self.PrePro_Debug.setEnabled(True)
        self.PrePro_Debug.setObjectName("PrePro_Debug")
        self.verticalLayout_2.addWidget(self.PrePro_Debug)
        self.tabWidget.addTab(self.Preprocessing, "")
        self.Blur = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Blur.sizePolicy().hasHeightForWidth())
        self.Blur.setSizePolicy(sizePolicy)
        self.Blur.setObjectName("Blur")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Blur)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.Blur)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.RemBlu_Input = QtWidgets.QLineEdit(self.Blur)
        self.RemBlu_Input.setObjectName("RemBlu_Input")
        self.horizontalLayout_32.addWidget(self.RemBlu_Input)
        self.RemBlu_Input_S = QtWidgets.QPushButton(self.Blur)
        self.RemBlu_Input_S.setMaximumSize(QtCore.QSize(30, 16777215))
        self.RemBlu_Input_S.setObjectName("RemBlu_Input_S")
        self.horizontalLayout_32.addWidget(self.RemBlu_Input_S)
        self.verticalLayout_3.addLayout(self.horizontalLayout_32)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.Blur)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.RemBlu_Csv = QtWidgets.QLineEdit(self.Blur)
        self.RemBlu_Csv.setObjectName("RemBlu_Csv")
        self.horizontalLayout_33.addWidget(self.RemBlu_Csv)
        self.RemBlu_Csv_S = QtWidgets.QPushButton(self.Blur)
        self.RemBlu_Csv_S.setMaximumSize(QtCore.QSize(30, 16777215))
        self.RemBlu_Csv_S.setObjectName("RemBlu_Csv_S")
        self.horizontalLayout_33.addWidget(self.RemBlu_Csv_S)
        self.verticalLayout_4.addLayout(self.horizontalLayout_33)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.RemBlu_Run = QtWidgets.QPushButton(self.Blur)
        self.RemBlu_Run.setObjectName("RemBlu_Run")
        self.horizontalLayout_10.addWidget(self.RemBlu_Run)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.AlphaSlider = QtWidgets.QSlider(self.Blur)
        self.AlphaSlider.setEnabled(False)
        self.AlphaSlider.setMaximum(10)
        self.AlphaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.AlphaSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.AlphaSlider.setObjectName("AlphaSlider")
        self.gridLayout.addWidget(self.AlphaSlider, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.Blur)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 1, 1, 1)
        self.AlphaVal = QtWidgets.QLabel(self.Blur)
        self.AlphaVal.setText("")
        self.AlphaVal.setObjectName("AlphaVal")
        self.gridLayout.addWidget(self.AlphaVal, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.Blur)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 1, 1, 1)
        self.PercToRemoved = QtWidgets.QLabel(self.Blur)
        self.PercToRemoved.setText("")
        self.PercToRemoved.setObjectName("PercToRemoved")
        self.gridLayout.addWidget(self.PercToRemoved, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.RemBlu_Filter = QtWidgets.QPushButton(self.Blur)
        self.RemBlu_Filter.setEnabled(False)
        self.RemBlu_Filter.setObjectName("RemBlu_Filter")
        self.horizontalLayout_9.addWidget(self.RemBlu_Filter)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.RemBlu_Debug = QtWidgets.QTextBrowser(self.Blur)
        self.RemBlu_Debug.setObjectName("RemBlu_Debug")
        self.verticalLayout_5.addWidget(self.RemBlu_Debug)
        self.tabWidget.addTab(self.Blur, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.credentials_2 = QtWidgets.QLineEdit(self.tab_4)
        self.credentials_2.setWhatsThis("")
        self.credentials_2.setAccessibleName("")
        self.credentials_2.setText("")
        self.credentials_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.credentials_2.setObjectName("credentials_2")
        self.gridLayout_7.addWidget(self.credentials_2, 1, 2, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.tab_4)
        self.label_64.setObjectName("label_64")
        self.gridLayout_7.addWidget(self.label_64, 0, 1, 1, 1)
        self.mail_2 = QtWidgets.QLineEdit(self.tab_4)
        self.mail_2.setText("")
        self.mail_2.setObjectName("mail_2")
        self.gridLayout_7.addWidget(self.mail_2, 0, 2, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.tab_4)
        self.label_65.setObjectName("label_65")
        self.gridLayout_7.addWidget(self.label_65, 0, 0, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.tab_4)
        self.label_66.setObjectName("label_66")
        self.gridLayout_7.addWidget(self.label_66, 1, 1, 1, 1)
        self.connect_2 = QtWidgets.QPushButton(self.tab_4)
        self.connect_2.setObjectName("connect_2")
        self.gridLayout_7.addWidget(self.connect_2, 1, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_7)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_19.addWidget(self.label_20)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.AD_model = QtWidgets.QLineEdit(self.tab_4)
        self.AD_model.setObjectName("AD_model")
        self.horizontalLayout_45.addWidget(self.AD_model)
        self.AD_model_B = QtWidgets.QPushButton(self.tab_4)
        self.AD_model_B.setMaximumSize(QtCore.QSize(30, 16777215))
        self.AD_model_B.setObjectName("AD_model_B")
        self.horizontalLayout_45.addWidget(self.AD_model_B)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_45)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_17.addWidget(self.label_19)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.AD_Dir = QtWidgets.QLineEdit(self.tab_4)
        self.AD_Dir.setObjectName("AD_Dir")
        self.horizontalLayout_44.addWidget(self.AD_Dir)
        self.AD_Dir_B = QtWidgets.QPushButton(self.tab_4)
        self.AD_Dir_B.setMaximumSize(QtCore.QSize(30, 16777215))
        self.AD_Dir_B.setObjectName("AD_Dir_B")
        self.horizontalLayout_44.addWidget(self.AD_Dir_B)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_44)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_14.addWidget(self.label_21)
        self.Exp_biigle = QtWidgets.QCheckBox(self.tab_4)
        self.Exp_biigle.setObjectName("Exp_biigle")
        self.horizontalLayout_14.addWidget(self.Exp_biigle)
        self.Exp_Pascal = QtWidgets.QCheckBox(self.tab_4)
        self.Exp_Pascal.setObjectName("Exp_Pascal")
        self.horizontalLayout_14.addWidget(self.Exp_Pascal)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.ConfidenceSlider = QtWidgets.QSlider(self.tab_4)
        self.ConfidenceSlider.setMaximum(10)
        self.ConfidenceSlider.setProperty("value", 3)
        self.ConfidenceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ConfidenceSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.ConfidenceSlider.setObjectName("ConfidenceSlider")
        self.horizontalLayout_22.addWidget(self.ConfidenceSlider)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem6)
        self.label_24 = QtWidgets.QLabel(self.tab_4)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_22.addWidget(self.label_24)
        self.Confidence_txt = QtWidgets.QLabel(self.tab_4)
        self.Confidence_txt.setMinimumSize(QtCore.QSize(20, 0))
        self.Confidence_txt.setObjectName("Confidence_txt")
        self.horizontalLayout_22.addWidget(self.Confidence_txt)
        self.verticalLayout_8.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem7)
        self.AD_run = QtWidgets.QPushButton(self.tab_4)
        self.AD_run.setObjectName("AD_run")
        self.horizontalLayout_18.addWidget(self.AD_run)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.AD_debug = QtWidgets.QTextBrowser(self.tab_4)
        self.AD_debug.setObjectName("AD_debug")
        self.verticalLayout_8.addWidget(self.AD_debug)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.credentials = QtWidgets.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.credentials.setFont(font)
        self.credentials.setText("")
        self.credentials.setEchoMode(QtWidgets.QLineEdit.Password)
        self.credentials.setObjectName("credentials")
        self.gridLayout_5.addWidget(self.credentials, 1, 2, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.tab_2)
        self.label_57.setObjectName("label_57")
        self.gridLayout_5.addWidget(self.label_57, 0, 1, 1, 1)
        self.mail = QtWidgets.QLineEdit(self.tab_2)
        self.mail.setAccessibleName("")
        self.mail.setText("")
        self.mail.setObjectName("mail")
        self.gridLayout_5.addWidget(self.mail, 0, 2, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.tab_2)
        self.label_58.setObjectName("label_58")
        self.gridLayout_5.addWidget(self.label_58, 0, 0, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.tab_2)
        self.label_59.setObjectName("label_59")
        self.gridLayout_5.addWidget(self.label_59, 1, 1, 1, 1)
        self.connect = QtWidgets.QPushButton(self.tab_2)
        self.connect.setObjectName("connect")
        self.gridLayout_5.addWidget(self.connect, 1, 0, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_5)
        self.horizontalLayout_83 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_83.setObjectName("horizontalLayout_83")
        self.label_60 = QtWidgets.QLabel(self.tab_2)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_83.addWidget(self.label_60)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_83.addItem(spacerItem8)
        self.Dir = QtWidgets.QLineEdit(self.tab_2)
        self.Dir.setObjectName("Dir")
        self.horizontalLayout_83.addWidget(self.Dir)
        self.Dir_b = QtWidgets.QPushButton(self.tab_2)
        self.Dir_b.setMaximumSize(QtCore.QSize(30, 16777215))
        self.Dir_b.setObjectName("Dir_b")
        self.horizontalLayout_83.addWidget(self.Dir_b)
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_83.addWidget(self.line_3)
        self.download = QtWidgets.QCheckBox(self.tab_2)
        self.download.setChecked(True)
        self.download.setObjectName("download")
        self.horizontalLayout_83.addWidget(self.download)
        self.verticalLayout_14.addLayout(self.horizontalLayout_83)
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_14.addWidget(self.line_2)
        self.horizontalLayout_81 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_81.setObjectName("horizontalLayout_81")
        self.Origin = QtWidgets.QPushButton(self.tab_2)
        self.Origin.setEnabled(False)
        self.Origin.setObjectName("Origin")
        self.horizontalLayout_81.addWidget(self.Origin)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_81.addItem(spacerItem9)
        self.Origin_txt = QtWidgets.QLineEdit(self.tab_2)
        self.Origin_txt.setObjectName("Origin_txt")
        self.horizontalLayout_81.addWidget(self.Origin_txt)
        self.verticalLayout_14.addLayout(self.horizontalLayout_81)
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_14.addWidget(self.line)
        self.horizontalLayout_78 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_78.setObjectName("horizontalLayout_78")
        self.Lab1 = QtWidgets.QPushButton(self.tab_2)
        self.Lab1.setEnabled(False)
        self.Lab1.setObjectName("Lab1")
        self.horizontalLayout_78.addWidget(self.Lab1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_78.addItem(spacerItem10)
        self.Lab1_txt = QtWidgets.QLineEdit(self.tab_2)
        self.Lab1_txt.setObjectName("Lab1_txt")
        self.horizontalLayout_78.addWidget(self.Lab1_txt)
        self.verticalLayout_14.addLayout(self.horizontalLayout_78)
        self.horizontalLayout_79 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_79.setObjectName("horizontalLayout_79")
        self.Lab2 = QtWidgets.QPushButton(self.tab_2)
        self.Lab2.setEnabled(False)
        self.Lab2.setObjectName("Lab2")
        self.horizontalLayout_79.addWidget(self.Lab2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_79.addItem(spacerItem11)
        self.Lab2_txt = QtWidgets.QLineEdit(self.tab_2)
        self.Lab2_txt.setText("")
        self.Lab2_txt.setObjectName("Lab2_txt")
        self.horizontalLayout_79.addWidget(self.Lab2_txt)
        self.verticalLayout_14.addLayout(self.horizontalLayout_79)
        self.horizontalLayout_82 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_82.setObjectName("horizontalLayout_82")
        self.Lab3 = QtWidgets.QPushButton(self.tab_2)
        self.Lab3.setEnabled(False)
        self.Lab3.setObjectName("Lab3")
        self.horizontalLayout_82.addWidget(self.Lab3)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_82.addItem(spacerItem12)
        self.Lab3_txt = QtWidgets.QLineEdit(self.tab_2)
        self.Lab3_txt.setText("")
        self.Lab3_txt.setObjectName("Lab3_txt")
        self.horizontalLayout_82.addWidget(self.Lab3_txt)
        self.verticalLayout_14.addLayout(self.horizontalLayout_82)
        self.horizontalLayout_77 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_77.setObjectName("horizontalLayout_77")
        self.Lab4 = QtWidgets.QPushButton(self.tab_2)
        self.Lab4.setEnabled(False)
        self.Lab4.setObjectName("Lab4")
        self.horizontalLayout_77.addWidget(self.Lab4)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_77.addItem(spacerItem13)
        self.Lab4_txt = QtWidgets.QLineEdit(self.tab_2)
        self.Lab4_txt.setText("")
        self.Lab4_txt.setObjectName("Lab4_txt")
        self.horizontalLayout_77.addWidget(self.Lab4_txt)
        self.verticalLayout_14.addLayout(self.horizontalLayout_77)
        self.horizontalLayout_80 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_80.setObjectName("horizontalLayout_80")
        self.reclass_cat = QtWidgets.QComboBox(self.tab_2)
        self.reclass_cat.setMinimumSize(QtCore.QSize(100, 0))
        self.reclass_cat.setObjectName("reclass_cat")
        self.horizontalLayout_80.addWidget(self.reclass_cat)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_80.addItem(spacerItem14)
        self.Run_b = QtWidgets.QPushButton(self.tab_2)
        self.Run_b.setObjectName("Run_b")
        self.horizontalLayout_80.addWidget(self.Run_b)
        self.verticalLayout_14.addLayout(self.horizontalLayout_80)
        self.horizontalLayout_84 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_84.setObjectName("horizontalLayout_84")
        self.label_61 = QtWidgets.QLabel(self.tab_2)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_84.addWidget(self.label_61)
        self.Remaining = QtWidgets.QLabel(self.tab_2)
        self.Remaining.setObjectName("Remaining")
        self.horizontalLayout_84.addWidget(self.Remaining)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_84.addItem(spacerItem15)
        self.label_62 = QtWidgets.QLabel(self.tab_2)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_84.addWidget(self.label_62)
        self.Speed = QtWidgets.QLabel(self.tab_2)
        self.Speed.setObjectName("Speed")
        self.horizontalLayout_84.addWidget(self.Speed)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_84.addItem(spacerItem16)
        self.label_63 = QtWidgets.QLabel(self.tab_2)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_84.addWidget(self.label_63)
        self.DoneNb = QtWidgets.QLabel(self.tab_2)
        self.DoneNb.setObjectName("DoneNb")
        self.horizontalLayout_84.addWidget(self.DoneNb)
        self.verticalLayout_14.addLayout(self.horizontalLayout_84)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem17, 0, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem18, 1, 0, 1, 1)
        self.Image = QtWidgets.QLabel(self.tab_2)
        self.Image.setObjectName("Image")
        self.gridLayout_6.addWidget(self.Image, 1, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem19, 1, 2, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem20, 2, 1, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_6)
        self.horizontalLayout_85 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_85.setObjectName("horizontalLayout_85")
        self.sel_lab1 = QtWidgets.QPushButton(self.tab_2)
        self.sel_lab1.setObjectName("sel_lab1")
        self.horizontalLayout_85.addWidget(self.sel_lab1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_85.addItem(spacerItem21)
        self.sel_lab2 = QtWidgets.QPushButton(self.tab_2)
        self.sel_lab2.setObjectName("sel_lab2")
        self.horizontalLayout_85.addWidget(self.sel_lab2)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_85.addItem(spacerItem22)
        self.sel_lab3 = QtWidgets.QPushButton(self.tab_2)
        self.sel_lab3.setObjectName("sel_lab3")
        self.horizontalLayout_85.addWidget(self.sel_lab3)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_85.addItem(spacerItem23)
        self.sel_lab4 = QtWidgets.QPushButton(self.tab_2)
        self.sel_lab4.setObjectName("sel_lab4")
        self.horizontalLayout_85.addWidget(self.sel_lab4)
        self.verticalLayout_14.addLayout(self.horizontalLayout_85)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_37 = QtWidgets.QLabel(self.tab)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_21.addWidget(self.label_37)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.BiRe_Csv = QtWidgets.QLineEdit(self.tab)
        self.BiRe_Csv.setObjectName("BiRe_Csv")
        self.horizontalLayout_38.addWidget(self.BiRe_Csv)
        self.BiRe_Csv_S = QtWidgets.QPushButton(self.tab)
        self.BiRe_Csv_S.setMaximumSize(QtCore.QSize(30, 16777215))
        self.BiRe_Csv_S.setObjectName("BiRe_Csv_S")
        self.horizontalLayout_38.addWidget(self.BiRe_Csv_S)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_38)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem24)
        self.BiRe_LabAnn = QtWidgets.QComboBox(self.tab)
        self.BiRe_LabAnn.setAcceptDrops(False)
        self.BiRe_LabAnn.setEditable(False)
        self.BiRe_LabAnn.setCurrentText("")
        self.BiRe_LabAnn.setObjectName("BiRe_LabAnn")
        self.horizontalLayout_30.addWidget(self.BiRe_LabAnn)
        self.verticalLayout_21.addLayout(self.horizontalLayout_30)
        self.verticalLayout_7.addLayout(self.verticalLayout_21)
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setLineWidth(4)
        self.line_4.setMidLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_7.addWidget(self.line_4)
        self.label_14 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_38 = QtWidgets.QLabel(self.tab)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_19.addWidget(self.label_38)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.BiRe_2DInput = QtWidgets.QLineEdit(self.tab)
        self.BiRe_2DInput.setObjectName("BiRe_2DInput")
        self.horizontalLayout_39.addWidget(self.BiRe_2DInput)
        self.BiRe_2DInput_S = QtWidgets.QPushButton(self.tab)
        self.BiRe_2DInput_S.setMaximumSize(QtCore.QSize(30, 16777215))
        self.BiRe_2DInput_S.setObjectName("BiRe_2DInput_S")
        self.horizontalLayout_39.addWidget(self.BiRe_2DInput_S)
        self.verticalLayout_19.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_12.addLayout(self.verticalLayout_19)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_42 = QtWidgets.QLabel(self.tab)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_24.addWidget(self.label_42)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.BiRe_soft = QtWidgets.QComboBox(self.tab)
        self.BiRe_soft.setAcceptDrops(False)
        self.BiRe_soft.setEditable(False)
        self.BiRe_soft.setCurrentText("")
        self.BiRe_soft.setObjectName("BiRe_soft")
        self.horizontalLayout_50.addWidget(self.BiRe_soft)
        self.verticalLayout_24.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_12.addLayout(self.verticalLayout_24)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_51 = QtWidgets.QLabel(self.tab)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_18.addWidget(self.label_51)
        self.BiRe_ExpName = QtWidgets.QLineEdit(self.tab)
        self.BiRe_ExpName.setObjectName("BiRe_ExpName")
        self.verticalLayout_18.addWidget(self.BiRe_ExpName)
        self.horizontalLayout_12.addLayout(self.verticalLayout_18)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.BiRe_2DRun = QtWidgets.QPushButton(self.tab)
        self.BiRe_2DRun.setObjectName("BiRe_2DRun")
        self.horizontalLayout_31.addWidget(self.BiRe_2DRun)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem25)
        self.verticalLayout_7.addLayout(self.horizontalLayout_31)
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_7.addWidget(self.line_5)
        self.label_15 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_7.addWidget(self.label_15)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_39 = QtWidgets.QLabel(self.tab)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_20.addWidget(self.label_39)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.BiRe_Model = QtWidgets.QLineEdit(self.tab)
        self.BiRe_Model.setObjectName("BiRe_Model")
        self.horizontalLayout_42.addWidget(self.BiRe_Model)
        self.BiRe_Model_B = QtWidgets.QPushButton(self.tab)
        self.BiRe_Model_B.setMaximumSize(QtCore.QSize(30, 16777215))
        self.BiRe_Model_B.setObjectName("BiRe_Model_B")
        self.horizontalLayout_42.addWidget(self.BiRe_Model_B)
        self.verticalLayout_20.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_11.addLayout(self.verticalLayout_20)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_40 = QtWidgets.QLabel(self.tab)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_22.addWidget(self.label_40)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.BiRe_sfm = QtWidgets.QLineEdit(self.tab)
        self.BiRe_sfm.setObjectName("BiRe_sfm")
        self.horizontalLayout_43.addWidget(self.BiRe_sfm)
        self.BiRe_sfm_B = QtWidgets.QPushButton(self.tab)
        self.BiRe_sfm_B.setMaximumSize(QtCore.QSize(30, 16777215))
        self.BiRe_sfm_B.setObjectName("BiRe_sfm_B")
        self.horizontalLayout_43.addWidget(self.BiRe_sfm_B)
        self.verticalLayout_22.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_11.addLayout(self.verticalLayout_22)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_41 = QtWidgets.QLabel(self.tab)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_23.addWidget(self.label_41)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.BiRe_ExportType = QtWidgets.QComboBox(self.tab)
        self.BiRe_ExportType.setAcceptDrops(False)
        self.BiRe_ExportType.setEditable(False)
        self.BiRe_ExportType.setCurrentText("")
        self.BiRe_ExportType.setObjectName("BiRe_ExportType")
        self.horizontalLayout_49.addWidget(self.BiRe_ExportType)
        self.verticalLayout_23.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_11.addLayout(self.verticalLayout_23)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.BiRe_3DRun = QtWidgets.QPushButton(self.tab)
        self.BiRe_3DRun.setObjectName("BiRe_3DRun")
        self.horizontalLayout_48.addWidget(self.BiRe_3DRun)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem26)
        self.verticalLayout_7.addLayout(self.horizontalLayout_48)
        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_7.addWidget(self.line_6)
        self.BiRe_Debug = QtWidgets.QTextBrowser(self.tab)
        self.BiRe_Debug.setObjectName("BiRe_Debug")
        self.verticalLayout_7.addWidget(self.BiRe_Debug)
        self.tabWidget.addTab(self.tab, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_27 = QtWidgets.QLabel(self.tab_6)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_15.addWidget(self.label_27)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.PR_input = QtWidgets.QLineEdit(self.tab_6)
        self.PR_input.setObjectName("PR_input")
        self.horizontalLayout_46.addWidget(self.PR_input)
        self.PR_input_B = QtWidgets.QPushButton(self.tab_6)
        self.PR_input_B.setMaximumSize(QtCore.QSize(30, 16777215))
        self.PR_input_B.setObjectName("PR_input_B")
        self.horizontalLayout_46.addWidget(self.PR_input_B)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_46)
        self.label_28 = QtWidgets.QLabel(self.tab_6)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_15.addWidget(self.label_28)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.PR_output = QtWidgets.QLineEdit(self.tab_6)
        self.PR_output.setObjectName("PR_output")
        self.horizontalLayout_47.addWidget(self.PR_output)
        self.PR_output_B = QtWidgets.QPushButton(self.tab_6)
        self.PR_output_B.setMaximumSize(QtCore.QSize(30, 16777215))
        self.PR_output_B.setObjectName("PR_output_B")
        self.horizontalLayout_47.addWidget(self.PR_output_B)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_47)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.PR_filter = QtWidgets.QCheckBox(self.tab_6)
        self.PR_filter.setObjectName("PR_filter")
        self.horizontalLayout_16.addWidget(self.PR_filter)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem27)
        self.PR_homogenize = QtWidgets.QCheckBox(self.tab_6)
        self.PR_homogenize.setObjectName("PR_homogenize")
        self.horizontalLayout_16.addWidget(self.PR_homogenize)
        self.label_29 = QtWidgets.QLabel(self.tab_6)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_16.addWidget(self.label_29)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.PR_data_config = QtWidgets.QLineEdit(self.tab_6)
        self.PR_data_config.setEnabled(False)
        self.PR_data_config.setObjectName("PR_data_config")
        self.horizontalLayout_51.addWidget(self.PR_data_config)
        self.PR_data_config_B = QtWidgets.QPushButton(self.tab_6)
        self.PR_data_config_B.setEnabled(False)
        self.PR_data_config_B.setMaximumSize(QtCore.QSize(30, 16777215))
        self.PR_data_config_B.setObjectName("PR_data_config_B")
        self.horizontalLayout_51.addWidget(self.PR_data_config_B)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_51)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem28)
        self.PR_run = QtWidgets.QPushButton(self.tab_6)
        self.PR_run.setObjectName("PR_run")
        self.horizontalLayout_20.addWidget(self.PR_run)
        self.verticalLayout_10.addLayout(self.horizontalLayout_20)
        self.line_7 = QtWidgets.QFrame(self.tab_6)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_10.addWidget(self.line_7)
        self.PR_debug = QtWidgets.QTextBrowser(self.tab_6)
        self.PR_debug.setObjectName("PR_debug")
        self.verticalLayout_10.addWidget(self.PR_debug)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_9.addWidget(self.label_23)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_13.addWidget(self.label_25)
        self.set_api_vol = QtWidgets.QLineEdit(self.tab_3)
        self.set_api_vol.setText("")
        self.set_api_vol.setObjectName("set_api_vol")
        self.horizontalLayout_13.addWidget(self.set_api_vol)
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_13.addWidget(self.label_26)
        self.set_api_LT = QtWidgets.QLineEdit(self.tab_3)
        self.set_api_LT.setText("")
        self.set_api_LT.setObjectName("set_api_LT")
        self.horizontalLayout_13.addWidget(self.set_api_LT)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem29)
        self.set_api_run = QtWidgets.QPushButton(self.tab_3)
        self.set_api_run.setObjectName("set_api_run")
        self.horizontalLayout_13.addWidget(self.set_api_run)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.line_11 = QtWidgets.QFrame(self.tab_3)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_9.addWidget(self.line_11)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.FN_Dir = QtWidgets.QLineEdit(self.tab_3)
        self.FN_Dir.setObjectName("FN_Dir")
        self.horizontalLayout_35.addWidget(self.FN_Dir)
        self.FN_Dir_B = QtWidgets.QPushButton(self.tab_3)
        self.FN_Dir_B.setMaximumSize(QtCore.QSize(30, 16777215))
        self.FN_Dir_B.setObjectName("FN_Dir_B")
        self.horizontalLayout_35.addWidget(self.FN_Dir_B)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_35)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.FN_Nav = QtWidgets.QLineEdit(self.tab_3)
        self.FN_Nav.setObjectName("FN_Nav")
        self.horizontalLayout_40.addWidget(self.FN_Nav)
        self.FN_Nav_B = QtWidgets.QPushButton(self.tab_3)
        self.FN_Nav_B.setMaximumSize(QtCore.QSize(30, 16777215))
        self.FN_Nav_B.setObjectName("FN_Nav_B")
        self.horizontalLayout_40.addWidget(self.FN_Nav_B)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_40)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.FN_Run = QtWidgets.QPushButton(self.tab_3)
        self.FN_Run.setObjectName("FN_Run")
        self.horizontalLayout_6.addWidget(self.FN_Run)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem30)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.line_9 = QtWidgets.QFrame(self.tab_3)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_9.addWidget(self.line_9)
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.ImgList_Dir = QtWidgets.QLineEdit(self.tab_3)
        self.ImgList_Dir.setObjectName("ImgList_Dir")
        self.horizontalLayout_41.addWidget(self.ImgList_Dir)
        self.ImgList_Dir_B = QtWidgets.QPushButton(self.tab_3)
        self.ImgList_Dir_B.setMaximumSize(QtCore.QSize(30, 16777215))
        self.ImgList_Dir_B.setObjectName("ImgList_Dir_B")
        self.horizontalLayout_41.addWidget(self.ImgList_Dir_B)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_41)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ImgList_Run = QtWidgets.QPushButton(self.tab_3)
        self.ImgList_Run.setObjectName("ImgList_Run")
        self.horizontalLayout_8.addWidget(self.ImgList_Run)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem31)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.line_10 = QtWidgets.QFrame(self.tab_3)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_9.addWidget(self.line_10)
        self.tools_debug = QtWidgets.QTextBrowser(self.tab_3)
        self.tools_debug.setObjectName("tools_debug")
        self.verticalLayout_9.addWidget(self.tools_debug)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_6.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.tab_5)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_6.addWidget(self.label_17)
        self.label_30 = QtWidgets.QLabel(self.tab_5)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_6.addWidget(self.label_30)
        self.label_18 = QtWidgets.QLabel(self.tab_5)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_6.addWidget(self.label_18)
        spacerItem32 = QtWidgets.QSpacerItem(20, 398, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem32)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.RawNav.toggled['bool'].connect(self.TextRefPath_S.setEnabled)
        self.RawNav.toggled['bool'].connect(self.TextRefPath.setEnabled)
        self.PR_homogenize.toggled['bool'].connect(self.PR_data_config.setEnabled)
        self.PR_homogenize.toggled['bool'].connect(self.PR_data_config_B.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ChubacApp"))
        self.label.setText(_translate("MainWindow", "Directory : "))
        self.PrePro_Input_S.setText(_translate("MainWindow", "..."))
        self.RawNav.setText(_translate("MainWindow", "Raw navigation ?"))
        self.label_3.setText(_translate("MainWindow", "Txt ref :"))
        self.TextRefPath_S.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "Output directory :"))
        self.PrePro_OutputPath_S.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "Nav name :"))
        self.NavName.setText(_translate("MainWindow", "output_nav"))
        self.CopyImage.setText(_translate("MainWindow", "Copy images ?"))
        self.PrePro_run.setText(_translate("MainWindow", "Launch"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Preprocessing), _translate("MainWindow", "Preprocessing"))
        self.label_6.setText(_translate("MainWindow", "Directory : "))
        self.RemBlu_Input_S.setText(_translate("MainWindow", "..."))
        self.label_8.setText(_translate("MainWindow", "Image blur (fac):"))
        self.RemBlu_Csv_S.setText(_translate("MainWindow", "..."))
        self.RemBlu_Run.setText(_translate("MainWindow", "Launch"))
        self.label_10.setText(_translate("MainWindow", "Alpha value:"))
        self.label_9.setText(_translate("MainWindow", "Percentage removed :"))
        self.RemBlu_Filter.setText(_translate("MainWindow", "Filter:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Blur), _translate("MainWindow", "Remove blur"))
        self.credentials_2.setToolTip(_translate("MainWindow", "Your Biigle api token"))
        self.credentials_2.setPlaceholderText(_translate("MainWindow", "*******************"))
        self.label_64.setText(_translate("MainWindow", "Email:"))
        self.mail_2.setPlaceholderText(_translate("MainWindow", "example@ifremer.fr"))
        self.label_65.setText(_translate("MainWindow", "Connection:"))
        self.label_66.setText(_translate("MainWindow", "Credentials:"))
        self.connect_2.setText(_translate("MainWindow", "Connect"))
        self.label_20.setText(_translate("MainWindow", "Model path:"))
        self.AD_model_B.setText(_translate("MainWindow", "..."))
        self.label_19.setText(_translate("MainWindow", "Images _directory:"))
        self.AD_Dir_B.setText(_translate("MainWindow", "..."))
        self.label_21.setText(_translate("MainWindow", "Export :"))
        self.Exp_biigle.setText(_translate("MainWindow", "Biigle"))
        self.Exp_Pascal.setText(_translate("MainWindow", "Pascal"))
        self.label_24.setText(_translate("MainWindow", "Confidence: "))
        self.Confidence_txt.setText(_translate("MainWindow", "0.30 %"))
        self.AD_run.setText(_translate("MainWindow", "Detect"))
        self.AD_debug.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Not yet ready</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Biigle DL"))
        self.credentials.setToolTip(_translate("MainWindow", "Your Biigle api token"))
        self.credentials.setPlaceholderText(_translate("MainWindow", "********************"))
        self.label_57.setText(_translate("MainWindow", "Email:"))
        self.mail.setPlaceholderText(_translate("MainWindow", "example@ifremer.fr"))
        self.label_58.setText(_translate("MainWindow", "Connection:"))
        self.label_59.setText(_translate("MainWindow", "Credentials:"))
        self.connect.setText(_translate("MainWindow", "Connect"))
        self.label_60.setText(_translate("MainWindow", "Directory:"))
        self.Dir_b.setText(_translate("MainWindow", "..."))
        self.download.setText(_translate("MainWindow", "Download ?"))
        self.Origin.setText(_translate("MainWindow", "Origin"))
        self.Lab1.setText(_translate("MainWindow", "Label 1"))
        self.Lab2.setText(_translate("MainWindow", "Label 2"))
        self.Lab3.setText(_translate("MainWindow", "Label 3"))
        self.Lab4.setText(_translate("MainWindow", "Label 4"))
        self.Run_b.setText(_translate("MainWindow", "Run"))
        self.label_61.setText(_translate("MainWindow", "Remaining: "))
        self.Remaining.setText(_translate("MainWindow", "0"))
        self.label_62.setText(_translate("MainWindow", "Speed: "))
        self.Speed.setText(_translate("MainWindow", "0"))
        self.label_63.setText(_translate("MainWindow", "Done: "))
        self.DoneNb.setText(_translate("MainWindow", "0"))
        self.Image.setText(_translate("MainWindow", "image"))
        self.sel_lab1.setText(_translate("MainWindow", "&Label 1"))
        self.sel_lab2.setText(_translate("MainWindow", "&Label 2"))
        self.sel_lab3.setText(_translate("MainWindow", "&Label 3"))
        self.sel_lab4.setText(_translate("MainWindow", "&Label 4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Biigle reclassifier"))
        self.label_37.setText(_translate("MainWindow", "Biigle report:"))
        self.BiRe_Csv_S.setText(_translate("MainWindow", "..."))
        self.label_14.setText(_translate("MainWindow", "Annotations -> 2D"))
        self.label_38.setText(_translate("MainWindow", "Image directory : "))
        self.BiRe_2DInput_S.setText(_translate("MainWindow", "..."))
        self.label_42.setText(_translate("MainWindow", "Software:"))
        self.label_51.setText(_translate("MainWindow", "Export layer name:"))
        self.BiRe_ExpName.setText(_translate("MainWindow", "Layer"))
        self.BiRe_2DRun.setText(_translate("MainWindow", "Launch"))
        self.label_15.setText(_translate("MainWindow", "Annotations -> 3D"))
        self.label_39.setText(_translate("MainWindow", "Model path : "))
        self.BiRe_Model_B.setText(_translate("MainWindow", "..."))
        self.label_40.setText(_translate("MainWindow", "sfm_data path : "))
        self.BiRe_sfm_B.setText(_translate("MainWindow", "..."))
        self.label_41.setText(_translate("MainWindow", "Export type:"))
        self.BiRe_3DRun.setText(_translate("MainWindow", "Launch"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Annotations conversion"))
        self.label_27.setText(_translate("MainWindow", "Input Path:"))
        self.PR_input_B.setText(_translate("MainWindow", "..."))
        self.label_28.setText(_translate("MainWindow", "Output path:"))
        self.PR_output_B.setText(_translate("MainWindow", "..."))
        self.PR_filter.setText(_translate("MainWindow", "Filter ?"))
        self.PR_homogenize.setText(_translate("MainWindow", "Homogenize ?"))
        self.label_29.setText(_translate("MainWindow", "Data types config:"))
        self.PR_data_config_B.setText(_translate("MainWindow", "..."))
        self.PR_run.setToolTip(_translate("MainWindow", "Launch the operation"))
        self.PR_run.setText(_translate("MainWindow", "Launch"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Post - Reprojection"))
        self.label_23.setText(_translate("MainWindow", "Biigle API: "))
        self.label_25.setText(_translate("MainWindow", "Volume : "))
        self.label_26.setText(_translate("MainWindow", "Label tree : "))
        self.set_api_run.setText(_translate("MainWindow", "Set"))
        self.label_11.setText(_translate("MainWindow", "Filter navigation:"))
        self.label_2.setText(_translate("MainWindow", "Image directory :"))
        self.FN_Dir_B.setText(_translate("MainWindow", "..."))
        self.label_7.setText(_translate("MainWindow", "Navigation: "))
        self.FN_Nav_B.setText(_translate("MainWindow", "..."))
        self.FN_Run.setText(_translate("MainWindow", "Run"))
        self.label_12.setText(_translate("MainWindow", "Image list:"))
        self.label_13.setText(_translate("MainWindow", "Image directory :"))
        self.ImgList_Dir_B.setText(_translate("MainWindow", "..."))
        self.ImgList_Run.setText(_translate("MainWindow", "Run"))
        self.tools_debug.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.875pt;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "tools"))
        self.label_16.setText(_translate("MainWindow", "ChubacApp V1.0.0"))
        self.label_17.setText(_translate("MainWindow", "Marin Marcillat, 2022, Ifremer Brest, BEEP-LEP, marinmarcillat@gmail.com"))
        self.label_30.setText(_translate("MainWindow", "Contributors: Lénaick Menot, Loic Van Audenhaege, Catherine Borremans"))
        self.label_18.setText(_translate("MainWindow", "Github (before Gitlab migration): https://github.com/marinmarcillat/CHUBACAPP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

